language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION='3.3'
    - php: 7.1
      env: SYMFONY_VERSION='3.3'
    - php: 7.1
      env: SYMFONY_VERSION='~4.0'
  allow_failures:
    - php: 7.1
      env: SYMFONY_VERSION='~4.0'


before_install:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update

before_script:
  - if [ "$SYMFONY_VERSION" = "~4.0" ]; then composer config minimum-stability dev; composer config prefer-stable true; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - true

after_success:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover clover; fi



