version: '2'
services:
  web:
    image: webdevops/php-apache-dev:ubuntu-16.04
    environment:
      WEB_DOCUMENT_ROOT: /app/web/
      WEB_DOCUMENT_INDEX: app_dev.php
      LDAPUI_APP_SECRET: TestDevSecret
      LDAPUI_CORS_ORIGIN: localhost
    depends_on:
      - ldap
    volumes:
      - ./src:/app:cached
    ports:
      - 8080:80
    networks:
      - ldap
  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: LdapUi
      LDAP_ADMIN_PASSWORD: password
      LDAP_DOMAIN: ldapui.com
    ports:
      - 389:389
    networks:
      - ldap
networks:
  ldap: {}