ldap_ui:
  hide:
    objects: []
    attributes: []

  acls:
    ROLE_USER:
      deny:
        objects:
          view: []
          create: []
          edit: []
          delete: []
        attributes:
          view: []
          create: []
          edit: []
          delete: []