ldap_tools:
    domains:
        test:
            domain_name: 'ldapui.com'
            bind_format: "cn=%%username%%,dc=ldapui,dc=com"
            base_dn: 'dc=ldapui,dc=com'
            servers: [ 'ldap' ]




        # example:
            # The FQDN of the domain
            # domain_name: 'example.com'

            # The username to use when binding to LDAP
            # If empty, credentials from login will be used.
            # username: 'admin'
            # password:

            # The simple name of the user will replace the %%username%%
            # Double %% needed to escape the normal parameter resolution in Symfony
            # bind_format: "CN=%%username%%,CN=Users,DC=example,DC=local"

            # The base DN for searches (ie. The default naming context: dc=example,dc=com)
            # base_dn: 'dc=example,dc=com'

            # An array of LDAP servers
            # servers: [ 'dc01' ]

            # Whether or not to initiate TLS when connecting to LDAP.
            # use_tls: false

            # The LDAP type for this domain. Choices are ad or openldap.
            # ldap_type: 'openldap'

            # The encoding to use for this domain.
            # encoding: 'UTF-8'

            # The elapsed time (in seconds) to attempt the initial connection to the LDAP server
            # connect_timeout: 5

            # server_selection

            # When more than one server is listed for a domain, choose which one is selected for the connection.
            # The possible choices are order (tried in the order they appear) or random.
            # server_selection: 'order'

            # Whether or not the connection should try to page results by default.
            # use_paging: true

            # The default page size to use for paging operations.
            # page_size: 1000

            # The LDAP_OPT_* constants and values to use when connecting to LDAP.
            # See: http://php.net/manual/en/function.ldap-set-option.php
            # ldap_options:
            #    ldap_opt_protocol_version: 3
            #    ldap_opt_referrals: 0
    security:
        roles:
            ROLE_SUPER_ADMIN:
              - 'Domain Admins'