imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ldapui/config.yml }

parameters:
    api_name: 'LDAPUi'
    api_description: 'The full description of the LDAPUi API'
    env(LDAPUI_LOCALE): 'en'
    env(LDAPUI_CORS_ORIGIN): 'http://localhost'

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
framework:
    #esi: ~
    translator: { fallbacks: ['en'] }
    secret: '%env(LDAPUI_APP_SECRET)%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%env(LDAPUI_LOCALE)%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

ldap_tools:
    general:
        cache_type: 'stash'
    security:
        default_role: ROLE_USER
        refresh_user_attributes: false
        refresh_user_roles: false
        guard:
            remember_me: true

nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    content_type:
        nosniff: true
    xss_protection:
        enabled: true
        mode_block: true
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
    assets:
        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
            output: vendor/jquery/js/jquery.js

        select2_js:
            inputs:
                - "%kernel.root_dir%/../vendor/select2/select2/dist/js/select2.full.js"
            output: vendor/select2/js/select2.js
        select2_js_l18n:
            inputs:
                - "%kernel.root_dir%/../vendor/select2/select2/dist/js/i18n/%env(LDAPUI_LOCALE)%.js"
            output: vendor/select2/js/select2-l18n.js
        select2_css:
            inputs:
                - "%kernel.root_dir%/../vendor/select2/select2/dist/css/select2.css"
            output: vendor/select2/css/select2.css

        jstree_js:
            inputs:
                - "%kernel.root_dir%/../vendor/vakata/jstree/dist/jstree.js"
            output: vendor/jstree/js/jstree.js
        jstree_css:
            inputs:
                - "%kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/style.css"
            output: vendor/jstree/css/style.css

        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.bundle.js"
            output: vendor/bootstrap/js/bootstrap.js
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css"
            output: vendor/bootstrap/css/bootstrap.css

        fontawesome_fonts_woff2:
            inputs:
                - "%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff2"
            output: vendor/fontawesome/fonts/fontawesome-webfont.woff2
        fontawesome_fonts_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff"
            output: vendor/fontawesome/fonts/fontawesome-webfont.woff
        fontawesome_fonts_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.ttf"
            output: vendor/fontawesome/fonts/fontawesome-webfont.ttf
        fontawesome_fonts_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.svg"
            output: vendor/fontawesome/fonts/fontawesome-webfont.svg
        fontawesome_fonts_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.eot"
            output: vendor/fontawesome/fonts/fontawesome-webfont.eot