# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LdapUiBundle\:
        resource: '../../src/LdapUiBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/LdapUiBundle/{Entity,Repository,Tests}'

    LdapUiBundle\Controller\:
        resource: '../../src/LdapUiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    object_voter:
        class: LdapUiBundle\Security\ObjectVoter
        autowire: true
        tags:
            - { name: security.voter }